### ISSUE TITLE
Compiling errors when using the command

### ISSUE THREAD

**Issue by WilliamWangPeng** [MohFakih2000/MandelCUDA#1]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm building your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/118403601-b8b82d80-b6a1-11eb-93c0-a8aa92878d46.png)

thank you  
best regards to you  
William

**Comment by themoefd** [comment]
Hello!
Thank you for writing.
The error is caused by the extra library I am using to create the image output. Since the library is included as source code, you will need to compile it too: the undefined references are due to the compiler not finding the functions from the library since it is not getting compiled (Very hand-wavey terms here but it is the gist of the issue)

The following command compiles both the library and my code:

nvcc qdbmp.cu main.cu -o a

Let me know if you have any other issues and thank you for checking out my project 😄
